//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public int Grade { get; set; }
        public Nullable<int> gender { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual GenderDetails GenderDetails { get; set; }
    }
}
